const locations = {"Mount Washington":{
                                        description:
                                        ["In the early history of Pittsburgh, Mount Washington was known as Coal Hill, but Coal Hill was actually on the south bank of the Monongahela River. Easy access to the Pittsburgh coal seam's outcrop near the base of Mt. Washington allowed several mines to operate there. Also, rock was quarried from the hill. Gray sandstone, for example, was quarried at Coal Hill for the second Allegheny County Courthouse.",
                                        "The original switchback trails that wound up the steep slopes of Mt. Washington were barely passable to a team of horses pulling a loaded wagon. Immigrants, predominantly from Germany, settled Mount Washington by the early 19th century and worked in the plants adjacent to the Monongahela River. They became weary of climbing steep footpaths and steps to their homes, from the river valley, after work. They remembered the standseilbahns (inclines) of their former country, and proposals were advanced to construct one or more of them along Coal Hill. The Monongahela Incline was the first of these to be built in 1869–1870. The Duquesne Incline opened to the public in May 1877, and it was one of four inclined planes climbing Mount Washington that carried passengers and freight to the residential area that had spread along the top of the bluff. As the hilltop communities were virtually inaccessible by any other means, many of Pittsburgh's inclines carried horses and wagons as well as foot passengers. All carried some light freight. A third incline, the Castle Shannon Incline, which closed in 1964, also served the hilltop community on Mt. Washington with a lower station at the corner of East Carson Street and Arlington Avenue, just east of the present Station Square Transit Station. This incline was closed by its owner, the Pittsburgh Railways Company, just prior to all of their streetcar and bus routes being taken over by the Port Authority.",
                                        "The Monongahela and Duquesne Inclines allow access to Mt. Washington's overlook of the downtown area of Pittsburgh. Tourists marvel at the view while riding two of only a few remaining inclines in the country. The inclines remain the best way for thousands of Pittsburghers on Mt. Washington to get to their jobs, entertainment and shopping in downtown Pittsburgh and Station Square."],

                                        image:"mw.jpg"},

                  "Schenley Park":{
                                    description:
                                    ["Created in 1889 with land donated by heiress Mary Schenley, the park now contains 456 acres of trails, woods, and attractions. A daily destination for university students, business-people, and outdoor enthusiasts, the park also hosts major annual events such as the Vintage Grand Prix and the Pittsburgh Race for the Cure.",
                                    "Visitors to Schenley Park can spend a morning at the remarkable Phipps Conservatory, enjoy lunch and a concert at the Schenley Park Café and Visitor Center, relax on Flagstaff Hill, play a round at the Bob O’Connor Golf Course, head to the Schenley Oval Sportsplex for ice skating or summer sports, or take a dip in the swimming pool. And of course, the trails offer a refreshing and convenient escape from the city.",
                                    "The Pittsburgh Parks Conservancy restored the Schenley Park Café and Visitor Center in 2001 and operates the space today with event and culinary partners, Eat'n Park Hospitality Group. In 2005, the Parks Conservancy worked with City of Pittsburgh crews to rehabilitate the Phipps Run stream channel that stretches from behind the Visitor Center down to Panther Hollow Lake. Restoration of the Panther Hollow Watershed is continuous, with the ultimate goal of restoring Panther Hollow Lake to a water quality that will once again allow for recreational use."],

                                    image:"sp.jpg"},

                  "Carnegie Mellon University":{
                                                description:
                                                ["The Carnegie Mellon University campus in Pittsburgh has served as the locale for many motion pictures. Alumnus George A. Romero filmed Creepshow (1982) in and around Margaret Morrison Carnegie Hall.Much of the on-campus scenes in the 2000 film Wonder Boys, starring Michael Douglas and Tobey Maguire, were filmed in Carnegie Mellon's campus. Other movies filmed at Carnegie Mellon include The Mothman Prophecies, Dogma, Lorenzo's Oil, Hoffa, The Dark Knight Rises, and Flashdance. The university is also featured prominently in the films Smart People, Monkey Shines, and in the anime Summer Wars. It was also referenced on an episode of The Simpsons, Weeds, and in the television film Mean Girls 2. Carnegie Mellon was identified as the university 'Rat' went to in the science fiction film The Core, as well as the university that one of the astronauts attended in the film Deep Impact.",
                                                "The musical Pippin was originally conceived by Stephen Schwartz as a student musical performed by the Scotch'n'Soda student theatre troupe.[66] Schwartz also collaborated with drama student John-Michael Tebelak to expand his master's thesis project titled Godspell, created under the direction of Lawrence Carra, into a musical.",
                                                "While enrolled at Carnegie Mellon, acting students Michael McKean and David Lander (class of 1969) created the characters 'Lenny & Squiggy'. The pair continued performing the characters in live comedy routines before joining the cast of the TV series Laverne and Shirley.",
                                                "In 2008, Carnegie Mellon professor Randy Pausch's 'Last Lecture' became a pop culture phenomenon. Based on a lecture he gave in September 2007 – shortly after he learned his cancer had metastasized – his book quickly rose to the top of bestseller lists around the country. Named in Time Magazine's 'Time 100' list of influential people, he died in July 2008 from pancreatic cancer."],

                                                image:"cmu.jpg"},

                  "Cathedral of Learning":{
                                            description:
                                            ["The University of Pittsburgh was well on the way to becoming an acropolis of neoclassical buildings on an Oakland hillside when John G. Bowman became the University's 10th chancellor in 1921. In those years following World War I, student enrollment had dramatically increased, causing a critical shortage of space. A 14-acre plot known as Frick Acres, which housed residences, gardens, and tennis courts, became the focus of Dr. Bowman's plans to erect a monumental building. A structure expanding upward, though unorthodox, would solve the growing University's problems of space and distance. More important, a tower would be a visible inspiration to all who approached the city. It would carry the message that education was the result of aspiring to great heights. The parallel lines of the truncated Gothic form, never meeting, would imply that learning is unending. The sweeping proportions would symbolize the spirit and achievement of Pittsburgh.  Architect Charles Z. Klauder translated these concepts into drawings that guided the placement of steel and stone."],

                                            image:"cathedral.jpg"},

                  "Point Park":{
                                description:
                                ["Point State Park (locally known as The Point) is a Pennsylvania state park on 36 acres (150,000 m2) in Downtown Pittsburgh, Allegheny County, Pennsylvania, USA, at the confluence of the Allegheny and Monongahela rivers, forming the Ohio River.",
                                "Built on land acquired via eminent domain from industrial enterprises in the 1950s, the park opened in August 1974[4] when construction was completed on its iconic fountain. Pittsburgh settled on the current design after rejecting an alternative plan for a Point Park Civic Center designed by Frank Lloyd Wright.",
                                "The park also includes the outlines and remains of two of the oldest structures in Pittsburgh, Fort Pitt and Fort Duquesne. The Fort Pitt Museum, housed in the Monongahela Bastion of Fort Pitt, commemorates the French and Indian War (1754–63), in which the area soon to become Pittsburgh was a major battlefield. It was designated a National Historic Landmark in 1960 for its role in the strategic struggles between Native Americans, French colonists, and British colonists, for control of the Ohio River watershed."],

                                image:"pp.jpg"}
                  };

export default locations;
